version: '3'

networks:
    nginx-php-mysql-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - nginx-php-mysql-node

    # php
    php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/html
        networks:
            - nginx-php-mysql-node

    # mysql
    mysql-service:
        image: mysql:5.7
        container_name: mysql-container
        ports:
            - "2306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        environment:
          MYSQL_USER: admin
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: library
        networks:
            - nginx-php-mysql-node

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
        networks:
            - nginx-php-mysql-node